name: Java Continuious Intigration with Maven
on: 
   push: 
     branches: ["main"]
   pull_request: 
     branches: ["main"]
jobs:
  build:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Docker Image
        with: 
          image: anelkumar/docker
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
